### ISSUE TITLE
DLL Signing

### ISSUE THREAD

**Issue by nathonius** [starkbank/ecdsa-dotnet#10]
Hey, so we recently upgraded our version of SendGrid, which [consumes this lib](https://github.com/sendgrid/sendgrid-csharp/pull/1017).

Immediately got pinged by our security scans; we've had to downgrade since StarkbankEcdsa.dll is unsigned. Signed dlls are a requirement for us.

We didn't need the latest updates for SendGrid, just trying to stay current, so it's not an immediate concern, but I wanted to put it on your radar.

**Comment by aadilwani** [comment]
Any update ??

**Comment by cdottori-stark** [comment]
Hey! Our team will process this issue and fix the warning on our next release package, which is planned for mid January. We'll notify you and close the issue as soon as the new signed dll is online. Thanks for the input!

**Comment by chrisjcoan** [comment]
Hey @cdottori-stark - any chance this issue is fixed and a new release is going to be pushed soon?

**Comment by cdottori-stark** [comment]
Hey @chrisjcoan, we just published version 1.3.0 with the assembly signature. Can you check if this solved the issue?

**Comment by chrisjcoan** [comment]
Hey @cdottori-stark - Getting the following issue after I upgrade to the latest version (1.3.0):

`The type 'PublicKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

Tried adding a binding redirect to the app.config and also tried manually referencing the dll but get the same issue. Any ideas?

**Comment by jdonaireOFI** [comment]
> Hey @cdottori-stark - Getting the following issue after I upgrade to the latest version (1.3.0):
> 
> `The type 'PublicKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`
> 
> Tried adding a binding redirect to the app.config and also tried manually referencing the dll but get the same issue. Any ideas?

I have the same problem. Any solution?

**Comment by doowruc** [comment]
> Hey @cdottori-stark - Getting the following issue after I upgrade to the latest version (1.3.0):
> 
> `The type 'PublicKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`
> 
> Tried adding a binding redirect to the app.config and also tried manually referencing the dll but get the same issue. Any ideas?

I am also getting this.

**Comment by DeromirNeves** [comment]
This issue is currently under investigation by our team, but unfortunately until now we were not able to reproduce this error. Can any of you @chrisjcoan, @jdonaireOFI or @doowruc  help us providing more information on the environment you are using (OS version, .NET target version and whether SendGrid was added as NuGet dependency or Assembly)? Also a minimum example Visual Studio project that yields this message would be extremely helpful. Without any additional information this issue will be closed in a few weeks.

**Comment by doowruc** [comment]
@DeromirNeves  It looks like it's been resolved in SendGrid 9.23.0, released today, which now references starkbank-ecdsa 1.3.1.

SendGrid 9.22.0 references starkbank-ecdsa 1.2.0 - this combination gives the original strongly-named error

Upgrading to starkbank-ecdsa 1.3.1 gives the PublicKey reference error

Upgrading to SendGrid 9.23.0 compiles and runs

EDIT: My testing was all done in .Net 4.7.2, SendGrid added directly via NuGet

**Comment by DeromirNeves** [comment]
@doowruc thank you for your quick response.
