### ISSUE TITLE
Bitcoin Der signiture - System.ArgumentException: nBytes must be < 160

### ISSUE THREAD

**Issue by bsubasic** [starkbank/ecdsa-dotnet#11]
I'm trying to parse Bitcoin Der signatures from the blockchain, and for some of them I'm getting those exceptions. 
The signatures seem valid to me when I check them manually.

Signature.fromDer(BinaryAscii.binaryFromHex("VALUE DISPLAYED BELOW"))

```
Exception: Signiture.fromDer(30440220d47ce4c025c35ec440bc81d99834a624875161a26bf56ef7fdc0f5d52f843ad102200c65c20bf81d88ec695182f3837f3991ffed1a15f1035f57381cc7aa457cab24)
System.ArgumentException: nBytes must be < 160
   at EllipticCurve.Utils.Der.removeInteger(Byte[] bytes)
   at EllipticCurve.Signature.fromDer(Byte[] bytes)

Exception: Signiture.fromDer(304402206e3da55b08f0c150a2651627c4cc2bd7378de34c4bb67a2b6113ea3e1bf8ad950220e773c89889544f29c9acaf6330dbd6f5f3e6abcfd1152ff706ff89faf92d10ae)
System.ArgumentException: nBytes must be < 160
   at EllipticCurve.Utils.Der.removeInteger(Byte[] bytes)
   at EllipticCurve.Signature.fromDer(Byte[] bytes)

Exception: Signiture.fromDer(30440220c231197255452a6c9ff8458ed7a703de445b0133dd601611eb1fec2a8c8c414f02203b74b4c495047ec77423a09347b98eb097c1c1897fc2825d03f51c9f4d697f55)
System.ArgumentException: nBytes must be < 160
   at EllipticCurve.Utils.Der.removeInteger(Byte[] bytes)
   at EllipticCurve.Signature.fromDer(Byte[] bytes)

Exception: Signiture.fromDer(30440220ac2dd06dd10f289a84f69bbb7b0482dbfa55ceb6af38f2fb5604b1ad22447a2f0220e080022fbb18535934bef72d44a30f37c7cece25112cd15433e8500e4099597b)
System.ArgumentException: nBytes must be < 160
   at EllipticCurve.Utils.Der.removeInteger(Byte[] bytes)
   at EllipticCurve.Signature.fromDer(Byte[] bytes)
```

**Comment by cdottori-stark** [comment]
Hi @bsubasic, could you provide some of the corresponding signed messages? Also how is the manual check being done?

**Comment by bsubasic** [comment]
By manually checking I mean looking into der definition and counting the length of R and S value of the final scriptSig.

**30** **44** **0220** d47ce4c025c35ec440bc81d99834a624875161a26bf56ef7fdc0f5d52f843ad1 **0220** 0c65c20bf81d88ec695182f3837f3991ffed1a15f1035f57381cc7aa457cab24

Results are from the inputs -> script on blockchain API
https://blockchain.info/multiaddr?active=1DXB1VrVYww4F8w7yjwHmHt8WVWjVpMmFN,1JmZw7Ds2FGHRwVKjyLRUK3CYHpX3e6rfB

signature (DER) | value
-- | --
sequence | 30
length | 44
integer | 02
length | 20
X | 2c b2 65 bf 10 70 7b f4 93 46 c3 51 5d d3 d1 6f c4 54 61 8c 58 ec 0a 0f f4 48 a6 76 c5 4f f7 13
integer | 02
length | 20
Y | 6c 66 24 d7 62 a1 fc ef 46 18 28 4e ad 8f 08 67 8a c0 5b 13 c8 42 35 f1 65 4e 6a d1 68 23 3e 82

described here: http://www.righto.com/2014/02/bitcoins-hard-way-using-raw-bitcoin.html

**Comment by leandro-stark** [comment]
Hi, @bsubasic!

The format is probably the issue in the piece of code you mentioned.

When you use the Signature.fromDer() method, what should be passed from the parameter is the DER (byte string), not the signature hex, as the example shows.

Here is a working example on how to use Signature.fromDer() on the hex signature you described:

 ``` c#
Signature.fromDer(
    byteStringFromHex(
"30440220d47ce4c025c35ec440bc81d99834a624875161a26bf56ef7fdc0f5d52f843ad102200c65c20bf81d88ec695182f3837f3991ffed1a15f1035f57381cc7aa457cab24"
        )
    )
```

If you have any questions, do not hesitate to ask!

Best,
