### ISSUE TITLE
bcrypt (windows) compatibility

### ISSUE THREAD

**Issue by chenuduss** [starkbank/ecdsa-dotnet#15]
I need to sign data using this library and validate data using bcrypt on windows in c ++ code. How do I store the public key and signature so that bcrypt functions successfully accept them and verify the signature?

**Comment by cdottori-stark** [comment]
I'm not familiar with bcrypt specifically, but the keys are usually stored/transported in PEM format and the signature in base64 format, for example:

```c#
using EllipticCurve;

PrivateKey privateKey = new PrivateKey();  // generating random private key
PublicKey publicKey = privateKey.publicKey();  // deriving public key from private key
string message = "message";
Signature signature = Ecdsa.sign(message, privateKey);

string publicKeyPem = publicKey.toPem();
string signatureBase64 = signature.toBase64();
```

**Comment by chenuduss** [comment]
signature.toBase64() - actually is base64 of DER, but BCryptVerifySignature not accept DER. 

Okay, I will cham to understand the problem further.
