### ISSUE TITLE
Please add support for byte array to be passed as message value to ecdsa.verify() and ecdsa.sign()

### ISSUE THREAD

**Issue by joele89** [starkbank/ecdsa-dotnet#16]
Please add support for byte array to be passed as message value to ecdsa.verify() and ecdsa.sign()

**Comment by leandro-stark** [comment]
Hi!

Thanks for the feedback!

This feature already is in our roadmap. We’ll let you know when it’s available.

If you have any additional questions, don’t hesitate to ask!

Best,

**Comment by Thaina** [comment]
@leandro-stark Pardon me but are there any method to do in the mean time?
