### ISSUE TITLE
Veracode Reported Security Flaws

### ISSUE THREAD

**Issue by raymer** [starkbank/ecdsa-dotnet#17]
Veracode is reporting 3 flaws with this library.

![image](https://user-images.githubusercontent.com/490221/137006787-ab0012c2-a499-4032-9e35-2dcef83164bd.png)

starkbankecdsa_dll.EllipticCurve.Utils.File.readBytes
starkbankecdsa_dll.EllipticCurve.Utils.File.read
These two have this flaw http://cwe.mitre.org/data/definitions/73.html

starkbankecdsa_dll.EllipticCurve.Utils.Integer.randomBetween
This has this flaw http://cwe.mitre.org/data/definitions/331.html

**Comment by massaru-stark** [comment]
Hello, Jonathan!

We analyzed the Veracode issues you informed and it seems to us that no actions are required:
- The File class is just a thin wrapper to System.IO.File, used to standardize the interface of the implementations of our ECDSA library in different languages, so you don't have to worry about it.
- The randonBetween issue only occurs when you pass the minimum and maximum parameter with the same values, which doesn't actually happen during the usage of the library, as ECDSA commands the minimum and maximum to be quite far apart.

If you have any additional question, don't hesite to ask!

**Comment by raymer** [comment]
I appreciate the quick reply! Just wanted to make sure I reported it to the maintainers. Thanks!
