### ISSUE TITLE
Cannot read starbank-exported pem file in dotnet

### ISSUE THREAD

**Issue by merijndejonge** [starkbank/ecdsa-dotnet#25]
I created a private key with the library and then export it to pem, like so:
```csharp
var privateKey = new PrivateKey("secp256k1", new BigInteger(my_seed));
var pem = privateKey.toPem();
```
I now want to import the private key to feed the standard dotnet core ECDsa algorithm:
```csharp
var key = ECDsa.Create();
key.ImportFromPem(pem);
````
This raises an exception about ASN1 corrupted data:

![image](https://user-images.githubusercontent.com/1928998/167884973-cd1c9aa1-78fd-47b4-9618-3001102ded43.png)

Is this a bug in the library, to am I doing things wrong?

**Comment by leandro-stark** [comment]
Hi, @merijndejonge!
The creation of the private key and its conversion to PEM format is correct with this block of code:

```c#
var privateKey = new PrivateKey("secp256k1", new BigInteger(my_seed));var pem = privateKey.toPem();

```

But the import of the private key it's not correct.

To import a private key using our ECDSA lib you can use:

- **fromPem()** function to import the private key in the PEM format;
- **fromDer()** function to import the private key in the DER format.

You can use the code below to follow as an example on how to create, convert and import a private key.

To create the private key:

```c#
PrivateKey privateKey1 = new PrivateKey();
```

To convert it to PEM or DER:

```c#
string pem = privateKey1.toPem();
byte[] der = privateKey1.toDer();

```
To import a private key in PEM or DER format:

```c#
PrivateKey privateKey2 = PrivateKey.fromPem(pem);
PrivateKey privateKey2 = PrivateKey.fromDer(der);
```

You can check it with more details in the [testPrivateKey.cs](https://github.com/starkbank/ecdsa-dotnet/blob/master/EcdsaDotNet/StarkbankEcdsaTests/testPrivateKey.cs) if you prefer.

If you have any questions, do not hesitate to ask!

Best

**Comment by merijndejonge** [comment]
Hi,
Thanks for helping me.
Unfortunately, I was perhaps not clear enough. My goal was to import the private key generated by StarkbankEcdsa library and import it into the **dot net core implementation of ECDSa** (i.e., System.Security.Cryptography.ECDsa). However, this gives the exception that I mentioned.

This is the code that I'm talking about:
```c#
var privateKey = new EllipticCurve.PrivateKey("secp256k1");
var pem = privateKey.toPem();

var key = System.Security.Cryptography.ECDsa.Create();
key.ImportFromPem(pem);
```
 
Any help is greatly appreciated.
