### ISSUE TITLE
Add support for netstandard1.3 and net452

### ISSUE THREAD

**Issue by childish-sambino** [starkbank/ecdsa-dotnet#4]
Looking to integrate with this library, but we have a couple target frameworks that are not supported:
* netstandard1.3
* net40
* net452

**Comment by childish-sambino** [comment]
Bump on this one. Approaching a delivery date and need to know if this will be looked at soon.

**Comment by cdottori-stark** [comment]
Just published the update on version 1.2.0.

Sorry about the huge delay, our development team completely overloaded on these past few weeks and we ended up leaving our public libraries a bit unattended, but we'll focus on clearing all pending issues today and then resume our usually quicker maintenance.

Thanks for the input!
